database:
  driverName: mysql
  host: localhost
  port: "3306"
  databaseName: test_eosc
  username: root
  password: root
  charset: utf8mb4
  loc: Asia/Shanghai
url: "wss://mainnet.infura.io/ws/v3/44542aa175d44232b84dc9f5f24f4b93"
